name: Packaging Tests

on: pull_request

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm

    - run: npm install
    - run: npm run test:packaging
